### ISSUE TITLE
a way to get around MemoryError?

### ISSUE THREAD

**Issue by inhahe** [sballas8/PoetRNN#1]
I'm trying to train on a relatively large file (1.7 MB) and "poems" with a poem_length of around 91 or greater raise MemoryError. I tried getting around this by doing the following:

```
for row in reader:
        try:
          poems.append(prep.poem_to_mat(row[0],poem_dict))
        except MemoryError:
          print ".",
```

which is a modification of lines 28-32 in train.py.

but after doing that, I get this:

Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main(params)
  File "train.py", line 36, in main
    labels.append(prep.generate_labels(poem,poem_dict))
  File "D:\py\PoetRNN-master\rnn\preprocessing.py", line 42, in generate_labels
    labels[-1]=dictionary['\t'] #label last character as tab to indicate the end has been reached.
IndexError: index -1 is out of bounds for axis 0 with size 0

I think it's a result of my try/except modification, but I'm not sure.
what do I need to do to successfully skip poems that are too long?

**Comment by sballas8** [comment]
My guess is that this error is caused by trying to feed in a poem that has length 0 (i.e. is the empty string). Although this doesn't seem to address your memory problem. That is, I suspect, caused by having long poems and a large vocabulary. To encode a poem of length `n` using a vocabulary of size `m` you need a matrix of size `nm`. How big is your vocabulary? 

Also, if you want to ignore poems that are long then you could try something like 

``` python
for row in reader:
    if len(row[0])>50:
        pass
    else:
        poems.append(prep.poem_to_mat(row[0],poem_dict))
```

You can play around with the number 50 until you find where the memory errors start to pop up. Hope this helps.

**Comment by inhahe** [comment]
Thanks, I added in a condition that len(row[0]) must not be 0, and then I stopped getting the index error. But filtering for rows greater than size X didn't work, I had it print the row size whenever it catches a MemoryError, and it output rows of all sizes. So I just stuck with catching MemoryError instead of trying to filter by row size, and it got past that stage (most of the poems passed).. then I got a MemoryError here (just below that area of code):

```
 for poem in poems:
       labels.append(prep.generate_labels(poem,poem_dict))
```

in the second line of the above.

i tried changing it to this:

```
 for poem in poems:
     try:
        labels.append(prep.generate_labels(poem,poem_dict))
        print ".",
    except MemoryError:
        print "*",
```

and it outputted a few lines of dots and then everything after it - many many more lines - were only asterisks, so it appears that most of the poems didn't work in the label appending phase, and the non working mode wasn't on a poem-by-poem basis, it just started not working after a certain number of poems. is there anything I can do for this?

**Comment by nathanegraham** [comment]
I'm also getting a memory error on a fairly small dataset: ~6MB of poems.

```
starting iteration  0
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main(params)
  File "train.py", line 76, in main
    fappend=params['fappend'],iter_to_update=params['iter_to_update'])
  File "/home/ec2-user/PoetRNN/rnn/rnn_classifier_trainer.py", line 113, in train
    drop_prob1=drop_prob1, drop_prob2=drop_prob2)
  File "/home/ec2-user/PoetRNN/rnn/RNN.py", line 228, in two_layer_LSTM_cost
    scores1, cache1 = LSTM.batch_forward(X, {'WLSTM': WLSTM1}, output_layer=False, drop_prob=drop_prob1)
  File "/home/ec2-user/PoetRNN/rnn/RNN.py", line 77, in batch_forward
    Hout = np.zeros((n, b, d))  # hidden representation of the LSTM (gated cell content)
MemoryError
```

Any ideas?
