### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by nathanegraham** [sballas8/PoetRNN#3]
Hi,

First off, very interesting script and approach. I just tried to run this on a 6MB csv of poetry and got this error:

```
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main(params)
  File "train.py", line 32, in main
    labels.append(prep.generate_labels(poem,poem_dict))
  File "/Users/Documents/research/machinelearning/PoetRNN/rnn/preprocessing.py", line 38, in generate_labels
    labels[-1]=dictionary['\t'] #label last character as tab to indicate the end has been reached. 
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by nathanegraham** [comment]
Nevermind - it fails if there's even one empty row. I removed any empty rows from the csv and it completed until I tried to use a larger dataset.
